Cleaup storehaus-redis
twitter/storehaus pull request #328
Opened 2016-09-15 20:36 UTC by BenFradet

2016-09-15 20:37 UTC, BenFradet commented
This will be made better once #310 is done.

2016-09-23 20:37 UTC, johnynek commented on storehaus-redis/src/main/scala/com/twitter/storehaus/redis/RedisHashStore.scala
> +    client.hGetAll(k).map { case e if e.isEmpty => None case xs => Some(Map(xs: _*)) }
can we make two lines:
```scala
.map {
  case e if e.isEmpty => None
  case xs => Some(Map(xs: _*))
}
```

2016-09-23 20:40 UTC, johnynek requested changes

2016-09-28 16:22 UTC, BenFradet commented on storehaus-redis/src/main/scala/com/twitter/storehaus/redis/RedisHashStore.scala
> +    client.hGetAll(k).map { case e if e.isEmpty => None case xs => Some(Map(xs: _*)) }
done :+1:

2016-10-06 20:40 UTC, BenFradet commented
ping @johnynek :smile:

2016-10-06 20:52 UTC, johnynek reviewed
sorry, I had a comment, but somehow it didn't get submitted. Maybe we don't have to fix it now, but we should file an issue, or maybe you can correct my understanding.

2016-10-06 20:52 UTC, johnynek commented on storehaus-redis/src/main/scala/com/twitter/storehaus/redis/RedisSortedSetStore.scala
> +    implicitly[Semigroup[Seq[(ChannelBuffer, Double)]]]
Is this really the semigroup that redis is doing? I tend to doubt it. Seems like the value is more like `Map[ChannelBuffer, Double]`. Can we add a test that the semigroup we declare here is consistent with how redis works?

We could do that by comparing `.multiMerge` here on a big set of items to what we would get from `MergeableStore.fromStore` and using the semigroup here.

2016-10-07 20:56 UTC, merged