Cleanup storehaus-testing
twitter/storehaus pull request #330
Opened 2016-10-09 17:43 UTC by BenFradet

2016-10-09 17:43 UTC, BenFradet commented
Finally done!

2016-10-10 23:28 UTC, johnynek requested changes

2016-10-10 23:28 UTC, johnynek commented on storehaus-testing/src/main/scala/com/twitter/storehaus/testing/Cleanup.scala
>  import scala.util.control.Exception.allCatch
allCatch predates `scala.util.Try`. Can we move to that?

2016-10-10 23:28 UTC, johnynek commented on storehaus-testing/src/main/scala/com/twitter/storehaus/testing/Cleanup.scala
> +      .map(c => allCatch.either(c.cleanup()).left.map((c, _)))
```scala
.foreach { c =>
  Try(c.cleanup()).recover {
    case error => println(s"failed to cleanup $c: ${error.getMessage}")
  }
}
```

2016-10-12 20:54 UTC, BenFradet commented
@johnynek updated :+1: 
I chose to ignore mima regarding storehaus-testing, do you agree?

2016-10-12 21:47 UTC, johnynek approved these changes

2016-10-12 21:47 UTC, merged

2016-10-12 21:47 UTC, johnynek commented
Thanks!