Clean up build to prep for 2.12
twitter/storehaus pull request #335
Opened 2016-12-10 16:03 UTC by sritchie

This PR:

- Adds `codecov.io` badges and support to the build
- Adds a Gitter storehaus channel webhook for build status updates -> Gitter
- enables caching in the travis build
- adds build, scaladex, gitter and code coverage badges to the README
- upgrades sbt to 0.13.13 and fixes deprecation warnings
- upgrades plugins like mima, jmh to latest versions
- kills old, deprecated doc tasks (I'll add a microsite soon)

This should get us ready for 2.12.0 once the relevant deps are in place.

2016-12-11 21:12 UTC, johnynek requested changes
looks good other than the minor change on mima.

2016-12-11 21:12 UTC, johnynek commented on project/plugins.sbt
> +addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "0.1.11")
can we bump this to `0.1.12`? I think that's the latest with a bugfix we found.

2016-12-11 21:37 UTC, sritchie commented
@johnynek done!

2016-12-11 21:39 UTC, johnynek commented
looks like it does not build.

2016-12-11 21:42 UTC, sritchie commented
Will fix when I get on a real computer

2016-12-11 21:55 UTC, sritchie commented
Okay @johnynek, NOW we should be good. That version bump killed some keys that we were importing (but not using). All tidied up now.

2016-12-11 22:43 UTC, sritchie commented
Build just needed a kick, @johnynek. Good to go now when tests pass.

2016-12-11 23:06 UTC, sritchie commented
Hmm, seems to be getting stuck after the kafka tests.

2016-12-12 00:56 UTC, sritchie commented
Nice @johnynek... looks like that upgrade DID catch two more binary incompatibilities. We have a TON of those now, btw. Definite version bump required.

2016-12-12 01:07 UTC, johnynek approved these changes
:+1:

2016-12-12 01:07 UTC, johnynek commented on build.sbt
> +    exclude[MissingClassProblem]("com.twitter.storehaus.kafka.JavaFutureToTwitterFutureConverter$Closed$"),
I think this code got migrated to bijection anyway, so we can use that on the next bump.

2016-12-12 01:10 UTC, johnynek commented on build.sbt
> +    exclude[MissingClassProblem]("com.twitter.storehaus.kafka.JavaFutureToTwitterFutureConverter$Closed$"),
Added #337

2016-12-12 03:15 UTC, merged